modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cech12/CeramicShears/issues"
[[mods]]
    modId="ceramicshears"
    version="${file.jarVersion}"
    displayName="Ceramic Shears"
    displayURL="https://github.com/cech12/CeramicShears"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds Ceramic Shears.
    '''